# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(357, 299)
        Form.setMinimumSize(QtCore.QSize(357, 299))
        Form.setMaximumSize(QtCore.QSize(357, 299))
        self.btn = QtWidgets.QPushButton(Form)
        self.btn.setGeometry(QtCore.QRect(130, 260, 101, 23))
        self.btn.setStyleSheet("QPushButton { border: none; }\n"
"\n"
"#btn {\n"
"     background-color: rgb(0, 255, 0);\n"
"    border-radius: 10px;        \n"
"}\n"
"#btn:pressed {\n"
"    background-color: rgb(255, 0, 0);\n"
"}")
        self.btn.setObjectName("btn")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(16, 22, 321, 221))
        self.label.setText("")
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Random circle"))
        self.btn.setText(_translate("Form", "НАЖМИ МЕНЯ"))
